---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-example
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        demo: hello-world
      annotations:
        demo: "Hello CNCF Webinar Attendees!"
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: podinfo
        downwardAPI:
          items:
            - path: labels
              fieldRef:
                fieldPath: metadata.labels
            - path: annotations
              fieldRef:
                fieldPath: metadata.annotations
      containers:
      - name: nginx
        image: enginex:latest
        ports:
        - protocol: TCP
          containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: podinfo
          mountPath: /etc/podinfo
        env:
        - name: KUBE_KUBELET
          valueFrom:
            fieldRef: 
              fieldPath: spec.nodeName
        - name: APP_EXAMPLE
          value: hello $(KUBE_KUBELET) world! 
        - name: APP_MESSAGE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['demo']
        - name: APP_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
